name: flutterassignment

description: Kgp2 SS Flutter Development Internship Assignment.
  Expected to create a demo app which contains 2 features - 
  1. Verify bad(Profanity) words when ever you are typing on textfield.
  2. Verify nudity content of Images.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  fontresoft:
    git:
      url: git@github.com:kenresoft/fontresoft.git
      ref: master
  cupertino_icons: ^1.0.5
  go_router: ^6.5.3
  flutter_riverpod: ^2.3.2
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.2

  image_picker: ^0.8.7+1
  shared_preferences: ^2.1.0
  json_annotation: ^4.8.0

  fluttertoast: ^8.2.1

  http: ^0.13.5
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  flutter_launcher_icons: ^0.12.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    #- assets/images/
    #- assets/icons/